Repository SEQAQ/qaq-react, pull requests merged in 2020-09, with the labels that each got.

#1 fix: bump eslint to ^6.6.0
  package.json
  src/App.test.js
  yarn.lock
Labels: bug

#2 fix: change npm into yarn
  package-lock.json
  package.json
  src/services/userServices.js
  src/utils/ajax.js
  src/utils/config.js
  yarn.lock
Labels: bug, enhancement

#3 doc: add getting started in README.md
  .gitignore
  README.md
Labels: documentation

#7 feat: user activity page
  .github/workflows/build.yml
  README.md
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/PrivateRoute.js
  src/Router.js
  src/component/Avatar/Avatar.js
  src/component/Button/FollowButton.js
  src/component/ProfileHeader/ProfileHeader.css
  src/component/ProfileHeader/ProfileHeader.js
  src/index.css
  src/utils/theme.js
  src/views/Activity/Activity.css
  src/views/Activity/Activity.js
  yarn.lock
Labels: enhancement

#10 feat: dynamic follow button
  .eslintrc
  src/App.js
  src/PrivateRoute.js
  src/Router.js
  src/component/Button/FollowButton.js
  src/component/ProfileHeader/ProfileHeader.js
  src/services/userServices.js
  src/utils/ajax.js
  src/utils/config.js
Labels: enhancement

#17 feat: activity feed card, including comment button, vote button group
  .eslintrc
  .eslintrc.js
  README.md
  package.json
  src/App.js
  src/PrivateRoute.js
  src/Router.js
  src/component/Avatar/Avatar.js
  src/component/Bar/ActionBar.js
  src/component/Bar/index.js
  src/component/Button/CommentButton.js
  src/component/Button/FollowButton.js
  src/component/Button/VoteButtonGroup.js
  src/component/Button/VoteButtonGroup.sass
  src/component/Button/index.js
  src/component/Card/FeedItem.js
  src/component/Card/FeedItem.sass
  src/component/Card/index.js
  src/component/Profile/ProfileHeader.css
  src/component/Profile/ProfileHeader.js
  src/index.css
  src/index.js
  src/services/userServices.js
  src/utils/style.js
  src/utils/theme.js
  src/views/Activity/Activity.js
  yarn.lock
Labels: enhancement

#18 Create dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#24 chore(ci): add npm packages cache to ci runner
  .eslintrc.js
  .github/workflows/build.yml
Labels: CI
